name: Build Vial firmware

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 'Vial Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: vial-kb/vial-qmk
      qmk_ref: vial
      # overwrite content of qmk.json with vial.json to build vial firmware - will not be committed anyways
      preparation_command: mv -f vial.json qmk.json

  publish:
    name: 'Vial Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
    with:
      release_name: latest-vial
